apiVersion: v1
kind: Pod
metadata:
  generateName: jx-git-operator-5c6bcd66fc-
  labels:
    app: jx-git-operator
    pod-template-hash: 5c6bcd66fc
  name: jx-git-operator-5c6bcd66fc-f5hqx
  namespace: jx-git-operator
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: jx-git-operator-5c6bcd66fc
      uid: 32b3e2c8-3665-468d-8794-905f969acbe7
spec:
  containers:
    - args:
        - echo 'no custom git initialisation scripts'; jx-git-operator
      command:
        - /bin/sh
        - -c
      env:
        - name: NO_RESOURCE_APPLY
          value: "true"
        - name: POLL_DURATION
          value: 20s
      image: gcr.io/jenkinsxio/jx-git-operator:0.0.138
      imagePullPolicy: IfNotPresent
      name: jx-git-operator
      resources:
        limits:
          cpu: 100m
          memory: 256Mi
        requests:
          cpu: 80m
          memory: 128Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: jx-git-operator-token-7hc57
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-jstrachan-tekton2-default-pool-09965e7b-9f2j
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: { }
  serviceAccount: jx-git-operator
  serviceAccountName: jx-git-operator
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: jx-git-operator-token-7hc57
      secret:
        defaultMode: 420
        secretName: jx-git-operator-token-7hc57
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: "2020-12-21T12:03:13Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2021-01-04T07:36:47Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2021-01-04T07:36:47Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2020-12-21T12:03:13Z"
      status: "True"
      type: PodScheduled
  containerStatuses:
    - containerID: docker://1756edcf497f86ae69d29511b8918b3a2146c9558f42cb0146c51afc05241d24
      image: gcr.io/jenkinsxio/jx-git-operator:0.0.138
      imageID: docker-pullable://gcr.io/jenkinsxio/jx-git-operator@sha256:c65b74210940389050c86191e52892196b2678d7d187b2baa62b88f1ba1f7e80
      lastState:
        terminated:
          containerID: docker://a05cfbb424a467e3a813b30aa3882f5dcf0d4cb0405413ab10513bc8f9170e54
          exitCode: 1
          finishedAt: "2021-01-04T07:36:46Z"
          reason: Error
          startedAt: "2020-12-23T03:06:32Z"
      name: jx-git-operator
      ready: true
      restartCount: 8
      started: true
      state:
        running:
          startedAt: "2021-01-04T07:36:46Z"
  hostIP: 10.154.0.21
  phase: Running
  podIP: 10.0.5.3
  podIPs:
    - ip: 10.0.5.3
  qosClass: Burstable
  startTime: "2020-12-21T12:03:13Z"
