---
apiVersion: v1
kind: Secret
metadata:
    name: balls
    annotations:
        size: small
        what: "put.in"
    labels:
        gitops/type: "top-secret"
data:
    some: YmFuYW5hcyBjb3VsZCBoZWxwCg==
