apiVersion: v1
kind: Pod
metadata:
  generateName: jx-git-operator-c6758b687-
  labels:
    app: jx-git-operator
    pod-template-hash: c6758b687
  name: jx-git-operator-c6758b687-pvkqp
  namespace: jx-git-operator
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: jx-git-operator-c6758b687
      uid: ad64ea4a-fa26-4076-953e-73584c81655c
spec:
  containers:
    - args:
        - echo 'no custom git initialisation scripts'; jx-git-operator
      command:
        - /bin/sh
        - -c
      env:
        - name: POLL_DURATION
          value: 20s
      image: gcr.io/jenkinsxio/jx-git-operator:0.0.143
      imagePullPolicy: IfNotPresent
      name: jx-git-operator
      resources:
        limits:
          cpu: 100m
          memory: 256Mi
        requests:
          cpu: 80m
          memory: 128Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: jx-git-operator-token-j94jn
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-cluster-1-default-pool-74753b82-8xjk
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: { }
  serviceAccount: jx-git-operator
  serviceAccountName: jx-git-operator
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: jx-git-operator-token-j94jn
      secret:
        defaultMode: 420
        secretName: jx-git-operator-token-j94jn
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: "2021-01-05T14:25:16Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2021-01-05T14:47:01Z"
      message: 'containers with unready status: [jx-git-operator]'
      reason: ContainersNotReady
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2021-01-05T14:47:01Z"
      message: 'containers with unready status: [jx-git-operator]'
      reason: ContainersNotReady
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2021-01-05T14:25:16Z"
      status: "True"
      type: PodScheduled
  containerStatuses:
    - containerID: docker://9d5238463759983c0bba9fb148327b3c44196240fd80d4d1f39d57b9f01007e0
      image: gcr.io/jenkinsxio/jx-git-operator:0.0.143
      imageID: docker-pullable://gcr.io/jenkinsxio/jx-git-operator@sha256:d01453e30857a59db5eaa5501503f8f102e8173946c842abb8b7328fde0345d5
      lastState:
        terminated:
          containerID: docker://9d5238463759983c0bba9fb148327b3c44196240fd80d4d1f39d57b9f01007e0
          exitCode: 1
          finishedAt: "2021-01-05T14:47:01Z"
          reason: Error
          startedAt: "2021-01-05T14:46:59Z"
      name: jx-git-operator
      ready: false
      restartCount: 9
      started: false
      state:
        waiting:
          message: back-off 5m0s restarting failed container=jx-git-operator pod=jx-git-operator-c6758b687-pvkqp_jx-git-operator(31003526-1503-4eb7-b22d-321466336b94)
          reason: CrashLoopBackOff
  hostIP: 10.154.0.28
  phase: Running
  podIP: 10.24.2.5
  podIPs:
    - ip: 10.24.2.5
  qosClass: Burstable
  startTime: "2021-01-05T14:25:16Z"
